---

- include: tasks/update_special_services.yml

- name: APT correct dependencies
  command: "apt-get -y -c {{ apt_conf }} {{ apt_flags }} -f install"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: APT upgrade
  command: "apt-get -y -c {{ apt_conf }} {{ apt_flags }} {{ apt_upgrade }}"
  environment:
    DEBIAN_FRONTEND: noninteractive

