
- name: Get list of upgrdable packages
  script: files/check_update_for_pkgs.sh
  environment:
    REPORT_DIR: "{{ report_dir }}"
    APT_UPGRADE: "{{ apt_upgrade }}"
    PKGS: "{{ pacemaker_pkgs }}"
  changed_when: update_flag.rc == 0
  failed_when: false
  register: update_flag

- include: tasks/update_pacemaker_action.yml
  when: update_flag.changed

