---

- name: Make sure report directory exists
  file:
    path: "{{ report_dir }}"
    state: directory

- name: Check if customizations were already gathered
  stat:
    path: "{{ report_dir }}/md5_results"
  register: md5_results

- include: verify_md5_action.yml
  when: not md5_results.stat.exists or
        md5_check is defined and
        md5_check

- name: Verify all customized and upgradable packages
  script: files/verify_upgradable_packages.sh
  environment:
    APT_CONF: "{{ apt_conf }}"
    CUSTOM_PKGS_FILE: "{{ report_dir }}/md5_results"
    UNKNOWN_CUSTOM_PKGS: "{{ unknown_custom_pkgs }}"
    UNKNOWN_UPGRADABLE_PKGS: "{{ unknown_upgradable_pkgs }}"
  ignore_errors: true
  register: md5_verify_result

- name: Show verification results
  debug:
    msg: "{{ md5_verify_result.stdout_lines }}"
  when:
    - md5_verify_result.stdout != ""

- name: Store the verification results
  shell: echo "{{ md5_verify_result.stdout }}" > "{{ report_dir }}/pkgs_verification_results"
  failed_when: false

- name: Fail if verification failed
  fail:
    msg: "[ERROR] Verification FAILED"
  when:
    - md5_verify_result.rc != 0

- name: Remove messages and leave only packages
  shell: echo "{{ md5_verify_result.stdout }}" | grep -v '^\[' | grep -v '^W\:'
  failed_when: false
  register: md5_verify_result

