---

- hosts: env_{{ env_id }}
  any_errors_fatal: true

  vars_files:
    - "vars/common.yml"
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps.yml"

  tasks:

    - include: tasks/apt_update.yml

    - include: tasks/apply_patches.yml

- include: restart_services.yml

- include: health_check.yml
