---

- hosts: env_{{ env_id }}
  any_errors_fatal: true
  vars:
    apt_flags: ""

  vars_files:
    - "vars/common.yml"
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps.yml"

  tasks:
    - name: Check mos_realease less than 9.0
      fail:
        msg: "[ERROR] This playbook can be ran only on MOS older than 9.0"
      when:
        - mos_release != "6.0"
        - mos_release != "6.1"
        - mos_release != "7.0"
        - mos_release != "8.0"

    - include: tasks/health_checks.yml
      when: health_check is undefined or
            health_check

    - include: tasks/apt_update.yml

    - name: Save current locked packages
      shell:  apt-mark showhold
      register: locked_packages

    - name: Hold keeped packages
      shell: echo "{{ keep_pkgs }}" | xargs apt-mark hold
      failed_when: false
      when:
        - keep_pkgs is defined
        - keep_pkgs

    - block:

      - include: tasks/gather_customizations.yml

      - include: tasks/verify_customizations.yml

      - include: tasks/verify_patches.yml

      - include: tasks/apt_upgrade.yml

      - include: tasks/apply_patches.yml

      always:
        - name: Restore locked packages
          shell: apt-mark showhold | xargs apt-mark unhold; echo "{{ locked_packages.stdout_lines }}" | xargs apt-mark hold
          failed_when: false

- include: restart_services.yml

- include: health_check.yml
