---

- hosts: env_{{ env_id }}
  any_errors_fatal: true
  vars:
    apt_flags: ""

  vars_files:
    - "vars/common.yml"
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps.yml"

  tasks:

    - include: tasks/apt_update.yml

    - include: tasks/apt_upgrade.yml

