---

- hosts: env_{{ env_id }}
  any_errors_fatal: true
  vars:
    apt_update: true
    apt_flags: ""

  vars_files:
    - "vars/common.yml"
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps.yml"

  tasks:

    - include: tasks/apt_update.yml

    - name: Save current locked packages
      shell:  apt-mark showhold
      register: locked_packages

    - name: Hold keeped packages
      shell: echo "{{ keep_pkgs }}" | xargs apt-mark hold
      failed_when: false
      when:
        - keep_pkgs is defined
        - keep_pkgs

    - block:

        - include: tasks/apt_upgrade.yml

      always:
        - name: Restore locked packages
          shell: apt-mark showhold | xargs apt-mark unhold; echo "{{ locked_packages.stdout_lines }}" | xargs apt-mark hold
          failed_when: false

