---

- hosts: env_{{ env_id }}
  any_errors_fatal: true
  vars:
    apt_flags: "-o Dir::Etc::sourcelist={{ apt_src_dir }}/{{ rollback }}.list -o Dir::Etc::sourceparts='-'"

  vars_files:
    - "vars/common.yml"
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps/rollback.yml"

  tasks:
    - name: Check mos_realease less than 9.0
      fail:
        msg: "[ERROR] This playbook can be ran only on MOS older than 9.0"
      when:
        - mos_release != "6.0"
        - mos_release != "6.1"
        - mos_release != "7.0"
        - mos_release != "8.0"

    - include: tasks/health_checks.yml
      when: health_check is undefined or
            health_check

    - include: tasks/apt_update.yml

    - name: Save current locked packages
      shell:  apt-mark showhold
      register: locked_packages

    - block:
      - include: tasks/gather_customizations.yml

      - include: tasks/verify_patches.yml

      - include: tasks/apt_upgrade.yml

      - include: tasks/apply_patches.yml

      always:
        - name: Restore locked packages
          shell: apt-mark showhold | xargs apt-mark unhold; echo "{{ locked_packages.stdout }}" | xargs apt-mark hold; exit 0

- include: restart_services.yml

