---

- hosts: env_{{ env_id }}
  any_errors_fatal: true

  vars_files:
    - "vars/common.yml"
    - "vars/mos_releases/{{ mos_release }}.yml"
    - "vars/steps.yml"

  tasks:

    - name: Get list of upgrdable packages
      script: files/check_update_for_pkgs.sh
      environment:
        REPORT_DIR: "{{ report_dir }}"
        APT_UPGRADE: "{{ apt_upgrade }}"
        PKGS: "{{ pacemaker_pkgs }}"
      changed_when: update_flag.rc == 0
      failed_when: false
      register: update_flag

    - include: tasks/update_pacemaker.yml
      when: update_flag.changed

