---
- hosts: fuel
  connection: local
  vars:
      rebuild_bootstrap: true
  vars_files:
    - "vars/common.yml"
    - "vars/mos_releases/{{ mos_release }}.yml"

  tasks:
  - name: Make backup directory exists on Fuel
    file:
      path: "{{ fuel_backup_dir }}"
      state: directory

  - name: Make back up the configuration of the Fuel
    shell: tar -czf "{{ fuel_backup_dir }}"/fuel_backup__$(date +%m.%d.%y__%H-%M-%S).tgz /var/lib/fuel
    when: mos_release == "6.1"

  - name: Install Fuel Octane
    yum:
      name: fuel-octane
      state: latest
    when: mos_release == "7.0" or
          mos_release == "8.0" or
          mos_release == "9.0" or
          mos_release == "9.1" or
          mos_release == "9.2"

  - name: Make back up the configuration of the Fuel
    shell: octane fuel-backup --to  "{{ fuel_backup_dir }}"/fuel_backup__$(date +%m.%d.%y__%H-%M-%S).tgz
    when: mos_release == "7.0" or
          mos_release == "8.0" or
          mos_release == "9.0" or
          mos_release == "9.1" or
          mos_release == "9.2"

  - include: tasks/update_old_fuel.yml
    when: mos_release == "6.1" or
          mos_release == "7.0" or
          mos_release == "8.0"

  - include: tasks/update_9x_fuel.yml
    when: mos_release == "9.0" or
          mos_release == "9.1" or
          mos_release == "9.2"
