---

env_release: "6.1"
fuel_url: "http://mirror.fuel-infra.org/mos"
apt_repos:
  - name: "GA"
    url: "{{ fuel_url }}/{{ os_platform }}-{{ env_release }}"
    suites:
      - "mos{{ env_release }}"
      - "mos{{ env_release }}-security"
      - "mos{{ env_release }}-holdback"
    type: "main restricted"
  - name: "mu-1"
    url: "{{ fuel_url }}/{{ os_platform }}-{{ env_release }}-mu-1"
    suites:
      - "mos{{ env_release }}-updates"
      - "mos{{ env_release }}-security"
      - "mos{{ env_release }}-holdback"
    type: "main restricted"
  - name: "mu-2"
    url: "{{ fuel_url }}/{{ os_platform }}-{{ env_release }}-mu-2"
    suites:
      - "mos{{ env_release }}-updates"
      - "mos{{ env_release }}-security"
      - "mos{{ env_release }}-holdback"
    type: "main restricted"
  - name: "mu-3"
    url: "{{ fuel_url }}/{{ os_platform }}-{{ env_release }}-mu-3"
    suites:
      - "mos{{ env_release }}-updates"
      - "mos{{ env_release }}-security"
      - "mos{{ env_release }}-holdback"
    type: "main restricted"
  - name: "mu-4"
    url: "{{ fuel_url }}/{{ os_platform }}-{{ env_release }}-mu-4"
    suites:
      - "mos{{ env_release }}-updates"
      - "mos{{ env_release }}-security"
      - "mos{{ env_release }}-holdback"
    type: "main restricted"
  - name: "mu-5"
    url: "{{ fuel_url }}/{{ os_platform }}-{{ env_release }}-mu-5"
    suites:
      - "mos{{ env_release }}-updates"
      - "mos{{ env_release }}-security"
      - "mos{{ env_release }}-holdback"
    type: "main restricted"
  - name: "mu-6"
    url: "{{ fuel_url }}/{{ os_platform }}-{{ env_release }}-mu-6"
    suites:
      - "mos{{ env_release }}-updates"
      - "mos{{ env_release }}-security"
      - "mos{{ env_release }}-holdback"
    type: "main restricted"
  - name: "mu-7"
    url: "{{ fuel_url }}/{{ os_platform }}-{{ env_release }}-mu-7"
    suites:
      - "mos{{ env_release }}-updates"
      - "mos{{ env_release }}-security"
      - "mos{{ env_release }}-holdback"
    type: "main restricted"
apt_sources_lists:
  - name: "fuel"
    path: "/etc/apt/sources.list.d/mos.list"

controller_pcs_resources:
    - p_heat-engine
    - p_neutron-plugin-openvswitch-agent
    - p_neutron-dhcp-agent
    - p_neutron-metadata-agent
    - p_neutron-l3-agent
    - p_ceilometer-agent-central
    - p_ceilometer-alarm-evaluator

controller_services:
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
    - nova-api
    - nova-cert
    - nova-conductor
    - nova-scheduler
    - nova-novncproxy
    - nova-objectstore
    - nova-consoleauth
    - cinder-api
    - cinder-scheduler
    - cinder-volume
    - cinder-backup
    - glance-api
    - glance-registry
    - neutron-server
    - ceilometer-api
    - ceilometer-collector
    - ceilometer-alarm-notifier
    - ceilometer-agent-notification
    - sahara-all
    - openstack-murano-api
    - openstack-murano-engine
    - apache2
    - swift-account-auditor
    - swift-account
    - swift-account-reaper
    - swift-account-replicator
    - swift-container-auditor
    - swift-container
    - swift-container-reconciler
    - swift-container-replicator
    - swift-container-sync
    - swift-container-updater
    - swift-object-auditor
    - swift-object
    - swift-object-reconstructor
    - swift-object-replicator
    - swift-object-updater
    - swift-proxy

compute_services:
    - nova-compute
    - neutron-plugin-openvswitch-agent
    - ceilometer-agent-compute
    - cinder-volume
    - cinder-backup
    - libvirtd
